/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/yggdrasil-network/yggdrasil-go/contrib/lib */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "lib.go"

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// Log callback. level: 0=trace, 1=debug, 2=info, 3=warn, 4=error
typedef void (*ygg_log_callback)(const char* msg, int level);

static void call_log_cb(ygg_log_callback cb, const char* msg, int level) {
	if (cb) cb(msg, level);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* ygg_last_error();
extern int ygg_start(char* configJSON, ygg_log_callback logCb);
extern int ygg_stop(int handle);
extern char* ygg_generate_config();
extern int ygg_send(int handle, void* data, int length);
extern int ygg_recv(int handle, void* buf, int bufLen);
extern int ygg_send_to(int handle, char* peerKeyHex, void* data, int length);
extern int ygg_recv_from(int handle, void* buf, int bufLen, char* peerKeyHexOut, int peerKeyHexOutLen);
extern int ygg_recv_from_timeout(int handle, void* buf, int bufLen, char* peerKeyHexOut, int peerKeyHexOutLen, int timeoutMs);
extern int ygg_add_peer(int handle, char* uri, char* sintf);
extern int ygg_remove_peer(int handle, char* uri, char* sintf);
extern int ygg_retry_peers_now(int handle);
extern char* ygg_listen(int handle, char* uri);
extern char* ygg_get_address(int handle);
extern char* ygg_get_subnet(int handle);
extern char* ygg_get_public_key(int handle);
extern int ygg_get_mtu(int handle);
extern int ygg_get_routing_entries(int handle);
extern char* ygg_get_version();
extern char* ygg_get_self_json(int handle);
extern char* ygg_get_peers_json(int handle);
extern char* ygg_get_paths_json(int handle);
extern char* ygg_get_tree_json(int handle);
extern char* ygg_get_sessions_json(int handle);
extern char* ygg_config_summary(char* configJSON);
extern void ygg_free_string(char* s);
extern void ygg_noop();
extern void ygg_noop_with_data(void* data, int length);

#ifdef __cplusplus
}
#endif
